version: '3.9'
services:
  loan_db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: 'loan-manager'
      POSTGRES_USER: 'weinber'
      POSTGRES_PASSWORD: 'weinber'
    ports:
      - 5430:5432
    expose:
      - '5430'
    volumes:
      - loan:/var/lib/postgresql/data
volumes:
  loan: